Basic db migration
joinbox/loopback-component-jb-migration pull request #2
Opened 2018-09-19 06:44 UTC by rcky

Sorry guys for the big PR and the weird code. I had to refactor a lot of stuff and add schema handling and debug the behavior of Postgres :(.

2018-09-19 08:10 UTC, rcky commented on src/MigrationTask.js
> +            return this.finalizeMigration(migration, result, null, transaction);
Not sure about this, I am not catching errors here to make sure it is not called twice

2018-09-19 09:33 UTC, linaGirl requested changes
Please add documentation to your code, it is not always clear what a method does or what the parameters are.

2018-09-19 09:33 UTC, linaGirl commented on README.md
> + as given by the `migration-mixin`.
Can you please link the corresponding source file?

2018-09-19 09:33 UTC, linaGirl commented on README.md
> +Tasks can be wrapped by a `MigrationTask` which will execute the task if needed and store the result
Please link the source files

2018-09-19 09:33 UTC, linaGirl commented on README.md
> +the `MigrationModel` reference and a `transaction` if it exists.
when does the transaction exist? is it a bad think if it doesn't exist? Please explain this a bit more

2018-09-19 09:33 UTC, linaGirl commented on README.md
> +**They don't!**
please add that one never should rely on the `search_path`

2018-09-19 09:33 UTC, linaGirl commented on index.js
> +const MigrationComponent = require('./src/MigrationComponent');
please add file extensions to absolute or relative imports. 

With the incoming `import .. from ..` and `export` statements this will gain relevance since only node.js is able to probe for extensions but not the browser. In the future source code will be shared more often between those two ecosystems. 

Especially code for the frontend should never rely on the fact that babel is able to probe for extensions since babel is going away in the next years.

cc @lkappeler 

i will publish the linter config today with the adjusted rule for this.

2018-09-19 09:33 UTC, linaGirl commented on index.js
> +module.exports = function(loopbackApp, { exposeAt = 'jb-migration'} = {}) {
missing block comment

2018-09-19 09:33 UTC, linaGirl commented on package.json
>      "description": "Simple migration component",
please be more descriptive

2018-09-19 09:33 UTC, linaGirl commented on package.json
> +        "test:base": "echo $NODE_DEBUG_OPTION && mocha $NODE_DEBUG_OPTION $WATCH_TESTS --recursive --check-leaks --full-trace --exit",
please don't rely on global packages. use the one in the node modules.

2018-09-19 09:33 UTC, linaGirl commented on src/MigrationQueue.js
> +const { MigrationError } = require('./error');
Please avoid using index files for one class.

2018-09-19 09:33 UTC, linaGirl commented on src/MigrationQueue.js
> +module.exports = class MigrationQueue {
Please add proper comments for all methods of the class

2018-09-19 09:33 UTC, linaGirl commented on src/MigrationTask.js
>  module.exports = class MigrationTask extends Task {
please add proper comments for each method

2018-09-19 09:33 UTC, linaGirl commented on src/Task.js
> +const fs = require('fs');
for the near future: https://nodejs.org/dist/latest/docs/api/fs.html#fs_fs_promises_api

2018-09-19 09:33 UTC, linaGirl commented on src/Task.js
> +        throw new MigrationError('Task:#run() not implemented');
Can you please add more information to the message? The identifier and maybe the version could be helpful

2018-09-19 09:33 UTC, linaGirl commented on src/Task.js
> +                throw new MigrationError(`Unmet depencency ${name} in dependency container`);
Can you please add more information to the message? The identifier and maybe the version could be helpful

2018-09-19 09:33 UTC, eventEmitter commented on src/Task.js
> +    async ensureDependencies(container, dependencyNames = this._getDependencies()) {
- When is this method called?
- What is the container?

please add documentation

2018-09-19 09:33 UTC, eventEmitter commented on src/Task.js
> +            if (!Object.prototype.hasOwnProperty.call(container, name)) {
Could a `Map` be of more use for the container as an object?

2018-09-19 09:33 UTC, eventEmitter commented on src/Task.js
> +        if(transaction) {
missing space `if(transaction)` vs ` if (transaction)`

2018-09-19 09:35 UTC, lkappeler approved these changes
In general, JS-Doc comments for the functions would be nice.

2018-09-19 09:35 UTC, lkappeler commented on README.md
> +Migration component for loopback.
May you want to note that it is implemented for postgres/SQL as a datasource?

2018-09-19 09:35 UTC, lkappeler commented on package.json
> +        "test:base": "echo $NODE_DEBUG_OPTION && mocha $NODE_DEBUG_OPTION $WATCH_TESTS --recursive --check-leaks --full-trace --exit",
Why do we need to echo the debug options?

2018-09-19 09:35 UTC, lkappeler commented on src/MigrationQueue.js
> +        const deps = await this.setupDependencies(dependencies);
The naming is a bit awkward here. You are passing the dependencies to build dependencies?

2018-09-19 09:35 UTC, lkappeler commented on src/Task.js
> +        return this.options.runAlways === true;
I got from the tests that the property defines whether a task can safely run multiple times.
I was confused on the naming here.

2018-09-19 09:35 UTC, lkappeler commented on src/Task.js
>          return new Promise((resolve, reject) => {
You could use `util.promisify` instead of wrapping a promise your own

2018-09-19 09:35 UTC, lkappeler commented on src/mixins/migration-mixin.js
> +        if (runAlways === true) {
I think I got something wrong on this, why can't a task be successful if it can run multiple times?

2018-09-19 09:35 UTC, lkappeler commented on src/tasks/ExecuteSQLStatementTask.js
> +        return this.statement
why did u added a line break here?

2018-09-19 09:35 UTC, lkappeler commented on src/tasks/postgres/CreateMigrationTable.js
> +              failed     TIMESTAMP DEFAULT NULL,
What is the thought behind tracking succeeded and failed time in two fields?

2018-09-19 09:35 UTC, lkappeler commented on docker-compose.testing.yml
> +version: '2'
How does the schema `migration_package` get created inside the container?

2018-09-19 09:46 UTC, rcky commented on package.json
> +        "test:base": "echo $NODE_DEBUG_OPTION && mocha $NODE_DEBUG_OPTION $WATCH_TESTS --recursive --check-leaks --full-trace --exit",
Good catch. Had to debug this.

2018-09-19 09:47 UTC, rcky commented on src/tasks/postgres/CreateMigrationTable.js
> +              failed     TIMESTAMP DEFAULT NULL,
You can rerun a failed migration.

2018-09-19 09:49 UTC, lkappeler requested changes
I accidentally approved before. I think to JS Doc Comments must be added.
Would be nice if you could answer the questions.
The suggested changes other than the Docs are up to you.

2018-09-19 14:14 UTC, rcky commented on package.json
> +        "test:base": "echo $NODE_DEBUG_OPTION && mocha $NODE_DEBUG_OPTION $WATCH_TESTS --recursive --check-leaks --full-trace --exit",
Ugh, we usually do this!

2018-09-19 14:17 UTC, rcky commented on src/Task.js
> +        throw new MigrationError('Task:#run() not implemented');
This is just to force people to implement the method.

2018-09-19 14:25 UTC, rcky commented on index.js
> +const MigrationComponent = require('./src/MigrationComponent');
I've got no problem with adding extensions to relative imports I don't see any reason for global ones (how do i know know how these packages look like internally?). 

To be honest I can't get rid of the feeling that these feedbacks are heavily biased by your work on `.mjs` and do not have any relevance for this code.

2018-09-19 14:27 UTC, rcky commented on src/mixins/migration-mixin.js
> +        if (runAlways === true) {
I had to go for a general way to handle this case. Feel free to extend the package accordingly.

2018-09-19 15:25 UTC, rcky commented
@lkappeler @eventEmitter Tackled most of the comments related to documentation. Just a hint: If we are working on a task without budget I'd prefer to get feedback about critical parts of the code and not formal things (I know this is my bad, since the PR is too big.)

2018-09-19 16:43 UTC, linaGirl approved these changes

2018-09-20 06:00 UTC, lkappeler approved these changes

2018-10-01 07:51 UTC, merged